### ISSUE TITLE
ffmpeg binary included

### ISSUE THREAD

**Issue by sneak** [HaschekSolutions/pictshare#111]
There is an ffmpeg binary in `bin`.  Without decompiling it, how am I to know it is safe to use?  For this reason I have to stop using the project - it would be better to use system ffmpeg and simply add a mention that it needs to be installed in the `README` (and install it in the `Dockerfile`).

**Comment by chrisiaut** [comment]
As stated [in the INSTALL.md](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/INSTALL.md) the binary is from https://www.johnvansickle.com/ffmpeg/ and you can check the hashes to verify it's not modified.

But of course you can link your own binary (like the one on your system) using the [CONFIG](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md) setting `FFMPEG_BINARY` which is the absolute path to your own binary. This is actually used in the Docker container because the provided binary is only for x64 CPUs and the Docker image for ARM will use the locally installed ffmpeg (if available)
