### ISSUE TITLE
Restricting uploading (password protection?)

### ISSUE THREAD

**Issue by peczony** [HaschekSolutions/pictshare#149]
Hi, thank you for the great work on the project!

I skimmed through the docs and couldn't understand how I could protect my instance from abuse. If it's open to the internet, anyone could host their content, including undesirable content (e.g. porn).

Is there any mechanism I could use to prevent this? I couldn't find any mention of passwords or tokens in the docs which could be used to prevent outside uploads. Ideally I would want to keep the instance only for myself & friends that I trust.

**Comment by geek-at** [comment]
Hey!

At the moment there is only the ["ALLOWED_SUBNET" config variable](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md) which limits uploads from an IP or IP space you define.

There is also a variable called "UPLOAD_CODE" that's not yet implemented but will act as a token that has to be specified in order to upload

**Comment by alexdatur** [comment]
i do it through nginx
 # pass secured
    location = / {
       auth_basic "Restricted Access";
       auth_basic_user_file /etc/nginx/.htpasswd;
       proxy_pass http://localhost:95;
       *
    }

    # to gallery without password
    location / {
        proxy_pass http://localhost:95;
        *
