### ISSUE TITLE
v2 Data directory not writable

### ISSUE THREAD

**Issue by feruzm** [HaschekSolutions/pictshare#77]
I am trying out v2 of pictshare and I noticed that upload page is not hidden if I enable

`define('UPLOAD_FORM_LOCATION', 'secret/upload');` 

also I get this error, any idea what folder needs some modification or what kind of permission change is necessary?

![image](https://user-images.githubusercontent.com/3015990/50472307-e44af800-09c0-11e9-8ed6-9ac66a07cc37.png)

**Comment by chrisiaut** [comment]
Well is your data directory writable for your webservers user? for testing you could chmod -R 777 data/ from within the root directory of pictshare

UPLOAD_FORM_LOCATION is not yet implemented

**Comment by feruzm** [comment]
that fixed it thanks!
got another 
![image](https://user-images.githubusercontent.com/3015990/50475142-4f4dfc00-09cc-11e9-9fc2-3b5e58c73379.png)

**Comment by chrisiaut** [comment]
very interesting. Can you upload the same file on our dev server https://dev.pictshare.net/ to see if it's a problem with your local installation?

**Comment by feruzm** [comment]
yes, looks like it is local installation issue
uploaded to your dev server but to local one not working

![image](https://user-images.githubusercontent.com/3015990/50475391-427dd800-09cd-11e9-91ab-f0a912336a9e.png)

**Comment by chrisiaut** [comment]
Ok I see you need to change your max upload settings since the file is too big for PHPs and Nginx default values

1. Edit your php.ini (probably somewhere in /etc/php/7.fpm/php.ini and change ```upload_max_filesize``` and ```post_max_size``` to a larger value
2. add ```client_max_body_size 20M;``` to your nginx config file for your pictshare instance. I also added this now in the [install guide](https://github.com/HaschekSolutions/pictshare/blob/v2/rtfm/INSTALL.md)

Thanks for testing!

**Comment by feruzm** [comment]
great, thanks! 🙏
